language: python
python:
    -"3.5"
install: python3 -m pip install -r requirements.txt
env:
    - CONFIG_PATH=tuneful.config.TravisConfig
before_script:
    - psql -c 'create database "tuneful-test";' -U postgres
script:
    - PYTHONPATH=. python3 tests/api_tests.py
